# Replica Count
# Image, both name and tag
# Service type and port

# @param: replicat-count
replicaCount: 1

# Settings for NGINX image
## @param image.name Nginx image name to use
## @param image.tag Nginx image tag to use
image: 
  name: nginx
  tag: "1.27.0" 

## Nginx Container ports
## 
## @param containerPorts.http
containerPorts: 
  http: 80

## Settings for NGINX service
##
## @param service.type The type of service in froont of Nginx service
## @param service.port The port of service exposed by Nginx service
service:
  enabled: true
  type: ClusterIP
  port: 80